name: Build and Deploy SQL Database Project
on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
          
    runs-on: ubuntu-latest  # Can also use windows-latest depending on your environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Install the SQLpackage tool
      - name: sqlpack install
        run: dotnet tool install -g microsoft.sqlpackage
    
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      # Build and Deploy SQL Project
      - name: Build and Deploy SQL Project
        uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ secrets.AZURE_CONN_STRING }}
          path: '../../GenocsSQL_Demo.sqlproj'
          action: 'publish'
          build-arguments: '-c Release'
          arguments: '/p:DropObjectsNotInSource=true'  # Optional: Customize as needed