/*
Deployment script for learn_demo database.

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "learn_demo"
:setvar DefaultFilePrefix "learn_demo"
:setvar DefaultDataPath "/var/opt/mssql/data/"
:setvar DefaultLogPath "/var/opt/mssql/data/"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[orders].[column_1] (SqlSimpleColumn) will not be renamed to order_id';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[products].[column_1] (SqlSimpleColumn) will not be renamed to product_id';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[orders].[column_1] (SqlSimpleColumn) will not be renamed to order_code';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[products].[column_1] (SqlSimpleColumn) will not be renamed to product_code';


GO
PRINT N'Dropping Default Constraint [dbo].[DF_catalog_created_at]...';


GO
ALTER TABLE [dbo].[catalog] DROP CONSTRAINT [DF_catalog_created_at];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping Default Constraint [dbo].[DF_catalog_id]...';


GO
ALTER TABLE [dbo].[catalog] DROP CONSTRAINT [DF_catalog_id];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping Default Constraint [dbo].[DF_catalog_counter]...';


GO
ALTER TABLE [dbo].[catalog] DROP CONSTRAINT [DF_catalog_counter];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
/*
The type for column id in table [dbo].[catalog] is currently  UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL but is being changed to  INT IDENTITY (1, 1) ROWGUIDCOL NOT NULL. There is no implicit or explicit conversion.
*/
GO
PRINT N'Starting rebuilding table [dbo].[catalog]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_catalog] (
    [id]          INT           IDENTITY (1, 1) ROWGUIDCOL NOT NULL,
    [name]        NVARCHAR (10) NOT NULL,
    [description] NVARCHAR (50) NULL,
    [counter]     INT           CONSTRAINT [DF_catalog_counter] DEFAULT ((0)) NOT NULL,
    [created_at]  DATETIME2 (7) CONSTRAINT [DF_catalog_created_at] DEFAULT (getdate()) NOT NULL,
    [last_update] DATETIME2 (7) NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_catalog1] PRIMARY KEY CLUSTERED ([id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[catalog])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_catalog] ON;
        INSERT INTO [dbo].[tmp_ms_xx_catalog] ([id], [name], [description], [counter], [created_at], [last_update])
        SELECT   [id],
                 [name],
                 [description],
                 [counter],
                 [created_at],
                 [last_update]
        FROM     [dbo].[catalog]
        ORDER BY [id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_catalog] OFF;
    END

DROP TABLE [dbo].[catalog];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_catalog]', N'catalog';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_catalog1]', N'PK_catalog', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
/*
The column employee_id on table [dbo].[sales] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/
GO
PRINT N'Starting rebuilding table [dbo].[sales]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_sales] (
    [employee_id] INT             IDENTITY (1, 1) NOT NULL,
    [department]  VARCHAR (50)    NULL,
    [sale_amount] DECIMAL (10, 2) NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_sales1] PRIMARY KEY CLUSTERED ([employee_id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[sales])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_sales] ON;
        INSERT INTO [dbo].[tmp_ms_xx_sales] ([employee_id], [department], [sale_amount])
        SELECT   [employee_id],
                 [department],
                 [sale_amount]
        FROM     [dbo].[sales]
        ORDER BY [employee_id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_sales] OFF;
    END

DROP TABLE [dbo].[sales];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_sales]', N'sales';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_sales1]', N'PK_sales', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating Table [dbo].[orders]...';


GO
CREATE TABLE [dbo].[orders] (
    [order_id]   INT           IDENTITY (1, 1) NOT NULL,
    [order_code] NVARCHAR (50) NULL,
    CONSTRAINT [PK_orders] PRIMARY KEY CLUSTERED ([order_id] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating Table [dbo].[products]...';


GO
CREATE TABLE [dbo].[products] (
    [product_id]   INT           IDENTITY (1, 1) NOT NULL,
    [product_code] NVARCHAR (35) NULL,
    CONSTRAINT [PK_products] PRIMARY KEY CLUSTERED ([product_id] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating Extended Property [dbo].[catalog].[id].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'primary_key', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'catalog', @level2type = N'COLUMN', @level2name = N'id';


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
GO
PRINT N'Update complete.';


GO
